name: kayabe_lims
description: Kayabe LIMS.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  dropdown_search: ^2.0.1
  equatable: ^2.0.3
  file_picker: ^4.3.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.9.2
  freezed_annotation: null
  get: ^4.3.8
  google_fonts: ^2.1.0
  google_sign_in: ^5.2.1
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.4.0
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  flutter_dotenv: ^5.0.2
  timelines: ^0.1.0
  persistent_bottom_nav_bar: ^4.0.2
  select_form_field: ^2.2.0
  shared_preferences: ^2.0.8
  
dev_dependencies:
  build_runner: null
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: null

flutter_icons:
  android: true
  ios: true
  image_path: "assets/playstore.png"

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - .env
  fonts:
    - family: DLabsIcons
      fonts:
        - asset: assets/fonts/DLabs-Icons.ttf
